@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь")
Person(manager, "Менеджер")
Person(consultant, "Консультант")
Person(employee, "Сотрудник банка")

System_Ext(operator, "Телеком-оператор")

Container_Ext(site, "Сайт", "PHP / React.js")
Container_Ext(gateway, "СМС-шлюз телеком-оператора")

Container_Boundary(ABC, "Автоматизированная банковская система (АБС)") {
    Component(ABClient, "Client", "Delphi")
    ContainerDb(ABCDB, "БД", "Oracle")

    Rel(ABClient, ABCDB, "Сохранение заявок")
}

Container_Boundary(internetBank, "Интернет-банк") {
    Component(internetBankGateway, "Gateway", "Nginx")

    Component(internetBankCore, "Core", "ASP.NET MVC 4.5")
    ContainerDb(internetBankDB, "БД", "MS SQL")

    Component(internetBankDeposite, "Deposite", "ASP.NET MVC 4.5")
    ContainerDb(internetBankDepositeDB, "БД", "MS SQL")

    Rel(internetBankGateway, internetBankCore, "Перенаправление \ получение счетов")
    Rel(internetBankGateway, internetBankDeposite, "Перенаправление \ взаимодействие с депозитами")

    Rel(internetBankCore, internetBankDB, "Сохранение данных")
    Rel(internetBankDeposite, internetBankDepositeDB, "Сохранение депозитов")
}


Container_Boundary(callCenter, "Система кол-центра") {
    Component(callCenterFrontend, "Сайт", "React.JS")
    Component(callCenterBackend, "Бекенд", "Java Spring Boot")
    ContainerDb(callCenterDB, "БД", "PostgreSQL")

    Rel(callCenterFrontend, callCenterBackend, "Взаимодействует с API")
    Rel(callCenterBackend, callCenterDB, "Сохраняет информацию")
}

Rel(site, internetBankGateway, "Получение списка депозитов")
Rel(internetBankDeposite, gateway, "Отправка СМС с кодом / решением по заявке")
Rel(internetBankDeposite, ABCDB, "Создание заявки о депозите")
Rel(ABClient, internetBankGateway, "Информирование о заявке")

Rel(gateway, operator, "СМС", "Отправка СМС")
Rel(user, site, "Получение списка депозитов")
Rel(user, internetBankGateway, "Открытие депозита по счету и сумме")
Rel(operator, user, "СМС", "Получение СМС")

Rel(consultant, callCenterFrontend, "Обрабатывает заявки и связывается с пользователем")
Rel(callCenterBackend, user, "Соединяет с пользователем")
Rel(consultant, ABClient, "Добавляет информацию по заявке от пользователя")

Rel(employee, ABClient, "Добавляет заявку на депозит")

Rel(manager, ABClient, "Обработка заявок")
@enduml
